version: 2

models:
  - name: ref_project_status
    description: The generated table contains project status information, consolidating new and existing records from the workspaces source (new data) and the REF_PROJECT_STATUS model (existing data). This table reflects the current status records of projects and flags those that have been deleted or no longer exist in the new data source.
    columns:
      - name: project_status_id
        description: This is the unique identifier for the project status. The value comes from the status_key in the original data source. If no value exists for status_key, -1 is assigned.
        tests:
          - unique
          - not_null
      - name: project_status_key
        description: This is a composite key combining the source system (in this case, 'MAVENLINK') with the project_status_id. This ensures that each project status key is unique within the context of the source system.
        tests:
          - not_null
      - name: project_status_name
        description: This is the name or message associated with the project status. If no message is available, the default value '$N/A' is assigned.
      - name: is_deleted
        description: Indicates whether the record has been marked as deleted. This column will have a value of 1 (true) if the project is no longer present in the new data source (ref_project_status_new), and 0 (false) if the record is still valid.
        tests:
          - accepted_values:
              values: [0, 1]
      - name: source_system
        description: Specifies the source system from which the project status originates. In this case, it will always be 'MAVENLINK', indicating that the data comes from this system.
        tests:
          - not_null
          - accepted_values:
              values: ['MAVENLINK']

  - name: ref_project
    description: "Contains information about projects, including their name, dates, status, and additional metadata."
    columns:
      - name: PROJECT_KEY
        description: "Primary key that uniquely identifies each project."
        tests:
          - not_null
          - unique

      - name: PROJECT_ID
        description: "Unique identifier for the project, used in the source system or for reporting purposes."
        tests:
          - not_null
          - unique

      - name: PROJECT_NAME
        description: "Descriptive name of the project."
        tests:
          - not_null

      - name: PROJECT_START_DATE
        description: "The start date of the project."
      - name: PROJECT_STATUS_ID
        description: "Identifier for the current status of the project, related to a status reference table."
        
      - name: SERVICE_LINE_ID
        description: "Identifier for the service line to which the project belongs."
        tests:
          - not_null

      - name: ROW_VALID_FROM
        description: "Date and time when this record became valid."
        #tests:
         # - not_null

      - name: ROW_VALID_TO
        description: "Date and time until this record is valid. If NULL, the record is still valid."
        #tests:
         # - not_null

      - name: IS_DELETED
        description: "Boolean flag indicating if the project has been logically deleted from the system."
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]

      - name: SOURCE_SYSTEM
        description: "The source system from which the project data originates."
        #tests:
         # - not_null
         # - unique
          